# Change these first
owner: danielitogomez # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: My CV Production
    url: https://danielitogomez.github.io/my-cv/
  - name: DulceDimagio Prod
    url: https://dulcedimagio.com/
  - name: Blog Hello-World-it Prod
    url: https://www.helloworld-it.com/
  - name: Homepage Prod
    url: https://danielitogomez.github.io/

assignees:
  - danielitogomez

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: pablokbs.github.io
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: danielitogomez
  introTitle: "**Websites status**"
  introMessage: Check the operation and status of our websites.
  navbar:
    - title: Status
      href: /upptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration